#!/bin/bash

restic-hdd cat config > /dev/null

restic-hdd --verbose backup --exclude-file /dir/restic-excludes.txt --files-from /dir/restic-includes.txt --skip-if-unchanged

restic-hdd --verbose forget --keep-weekly 4 --prune && restic-hdd --verbose check
