#!/usr/bin/bash

if restic-repo cat config &> /dev/null; then
    echo "BACKING UP"
    restic-repo backup \
        --exclude-file /path/to/restic-excludes.txt \
        --skip-if-unchanged
        $HOME
    echo ""
    echo "REMOVING SNAPSHOTS"
    restic-repo forget \
        --keep-within-weekly 1m \
        --keep-within-monthly 1y \
        --prune && restic-repo check
else
    echo "REPOSITORY NOT FOUND"
fi
